# Use root/example as user/password credentials
version: '3.1'

services:

    # redis:
    #     image: redis:latest
    #     restart: always
    #     ports:
    #         - 16379:6379
    
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/mongo:/data/db
        ports:
            - 27017:27017
        # command: mongod --smallfiles --logpath=/dev/null # --quiet
        command: mongod --logpath=/dev/null # --quiet

    # draph_zero:
    #     image: dgraph/dgraph:latest
    #     volumes:
    #     - type: volume
    #         source: dgraph
    #         target: /data/dgraph
    #         volume:
    #         nocopy: true
    #     ports:
    #     - 5080:5080
    #     - 6080:6080
    #     restart: on-failure
    #     command: dgraph zero --my=zero:5080
    # draph_server:
    #     image: dgraph/dgraph:latest
    #     volumes:
    #     - type: volume
    #         source: dgraph
    #         target: /data/dgraph
    #         volume:
    #         nocopy: true
    #     ports:
    #     - 8080:8080
    #     - 9080:9080
    #     restart: on-failure
    #     command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
    # draph_ratel:
    #     image: dgraph/dgraph:latest
    #     volumes:
    #     - type: volume
    #         source: dgraph
    #         target: /data/dgraph
    #         volume:
    #         nocopy: true
    #     ports:
    #     - 8000:8000
    #     command: dgraph-ratel

    # volumes:
    # dgraph:
      
# networks:
#   backend:
#     driver: bridge
